server:
  host: 0.0.0.0
  port: 8090
  write-timeout: 60s
  read-timeout: 60s
  idle-timeout: 60s
  allowed-origins: ["*"]
  log-level: debug
  btc-net: "mainnet"
  max-content-length: 4096
  health-check-interval: 300 # 5 minutes interval
delegation-transition:
  eligible-before-btc-height: 10
  allow-list-expiration-height: 10
staking-db:
  username: root
  password: example
  address: "mongodb://mongodb:27017"
  db-name: staking-api-service
  max-pagination-limit: 100
  logical-shard-count: 10
indexer-db:
  username: root
  password: example
  address: "mongodb://indexer-mongodb:27019"
  db-name: indexer-db
  max-pagination-limit: 100
queue:
  queue_user: user # can be replaced by values in .env file
  queue_password: password
  url: "rabbitmq:5672"
  processing_timeout: 5s
  msg_max_retry_attempts: 10
  requeue_delay_time: 300s # delay failed message requeue time in seconds
  queue_type: quorum
metrics:
  host: 0.0.0.0
  port: 2112
assets:
  max_utxos: 100
  ordinals:
    host: "http://ord-poc.devnet.babylonchain.io"
    port: 8888
    timeout: 1000
external_apis:
  coinmarketcap:
    api_key: ${COINMARKETCAP_API_KEY}
    base_url: "https://pro-api.coinmarketcap.com/v1"
    timeout: 10s  # http client timeout
    cache_ttl: 300s  # mongodb ttl
