name: Release Workflow

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string
      description:
        description: 'Release description'
        required: true
        type: string
      prerelease:
        description: 'Whether prerelease is enabled'
        required: true
        type: boolean
        default: false

jobs:
  call-reusable-release:
    uses: babylonlabs-io/.github/.github/workflows/reusable_github_release.yml@v0.13.0
    with:
      tag: ${{ inputs.tag }}
      description: ${{ inputs.description }}
      prerelease: ${{ inputs.prerelease }}
      build_command: |
        make install
      docker_image_name: babylonlabs/staking-api-service:${{ inputs.tag }}
    secrets: inherit